//+build !swipe

// Code generated by Swipe v2.0.0-beta6. DO NOT EDIT.

package transport

import (
	"io"
	"strings"

	"github.com/go-kit/kit/endpoint"
)

type ScraperRequestEndpointFactory struct {
	Option []ClientOption
	Path   string
}

func (f *ScraperRequestEndpointFactory) GetAvailabilityEndpointFactory(instance string) (endpoint.Endpoint, io.Closer, error) {
	if f.Path != "" {
		instance = strings.TrimRight(instance, "/") + "/" + strings.TrimLeft(f.Path, "/")
	}
	c, err := NewClientREST(instance, f.Option...)
	if err != nil {
		return nil, nil, err
	}
	return makeScraperRequestGetAvailabilityEndpoint(c), nil, nil

}

func (f *ScraperRequestEndpointFactory) GetResponceTimeEndpointFactory(instance string) (endpoint.Endpoint, io.Closer, error) {
	if f.Path != "" {
		instance = strings.TrimRight(instance, "/") + "/" + strings.TrimLeft(f.Path, "/")
	}
	c, err := NewClientREST(instance, f.Option...)
	if err != nil {
		return nil, nil, err
	}
	return makeScraperRequestGetResponceTimeEndpoint(c), nil, nil

}

func (f *ScraperRequestEndpointFactory) GetStatisticsEndpointFactory(instance string) (endpoint.Endpoint, io.Closer, error) {
	if f.Path != "" {
		instance = strings.TrimRight(instance, "/") + "/" + strings.TrimLeft(f.Path, "/")
	}
	c, err := NewClientREST(instance, f.Option...)
	if err != nil {
		return nil, nil, err
	}
	return makeScraperRequestGetStatisticsEndpoint(c), nil, nil

}
